name: Deploy to Production

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 178.128.172.154
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32432
          script: |
            cd /home/site/apps/polypoint/deployment/polypoint-deploy
            ./update-app.sh
